global:
  scrape_interval:     20s 
  evaluation_interval: 20s 

rule_files:

scrape_configs:

  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'crawler'

    static_configs:
      - targets: ['crawler:8000']

  - job_name: 'ui'

    static_configs:
      - targets: ['ui:8000']
