{
 "title": "otus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "UI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "web_pages_served",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "web_pages_served", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "web_page_gen_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "web_page_gen_time_sum", "legendFormat": "__auto" }
   ]
  },
  { "title": "Crawler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "crawler_pages_parsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "crawler_pages_parsed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "crawler_site_connection_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "crawler_site_connection_time_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "crawler_page_parse_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "crawler_page_parse_time_sum", "legendFormat": "__auto" }
   ]
  }
 ]
}